name: Promote module release bundle to TEST and STAGE

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      module-name:
        description: "Artifact ID of the module to promote (e.g. spring-boot-starter-aerospike)"
        required: true
        type: string
      version:
        description: Version to be promoted
        required: true
        type: string

jobs:
  promote-to-test-and-stage:
    name: Promote to TEST and to STAGE
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Setup JFrog CLI
        uses: step-security/setup-jfrog-cli@53aeacb709fce45d0baf69a13ec3342f7e2d71a9 # v5.1.0
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
          JF_PROJECT: ${{ vars.JFROG_PROJECT }}
        with:
          oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      - name: Promoting release bundle to TEST
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@b4b1e9dc89314a2d542f9d6fe0ee150ad06f9860 # v5.0.0
        with:
          bundle-name: ${{ inputs.module-name }}
          version: ${{ inputs.version }}
          environment: TEST
          jf-project: ${{ vars.JFROG_PROJECT }}

      - name: Promoting release bundle to STAGE
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@b4b1e9dc89314a2d542f9d6fe0ee150ad06f9860 # v5.0.0
        with:
          bundle-name: ${{ inputs.module-name }}
          version: ${{ inputs.version }}
          environment: STAGE
          jf-project: ${{ vars.JFROG_PROJECT }}
